services:
  db:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_DB: nutritionapp-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nutritionapppwd
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d nutritionapp-db -h 127.0.0.1']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

volumes:
  pg:
