name: ios
on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build-ios:
    runs-on: macos-14
    defaults:
      run:
        working-directory: apps/mobile
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install deps (workspaces)
        run: bun install

      - name: Prebuild iOS (no native install)
        run: bunx --bun expo prebuild -p ios --clean --no-install

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods -N
          cd ios && pod install --repo-update

      - name: Build .app (skip signing)
        run: |
          cd ios
          # Set your scheme; it usually matches the "name" in app.config.ts without spaces.
          SCHEME="AcmeMobile"
          xcodebuild -scheme "$SCHEME" -configuration Release -sdk iphoneos -derivedDataPath build CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
          APP_PATH=$(find build/Build/Products/Release-iphoneos -name "*.app" -maxdepth 1 -print -quit)
          echo "Found app at: $APP_PATH"
          mkdir -p payload/Payload
          cp -R "$APP_PATH" payload/Payload
          cd payload
          zip -yr ../AcmeMobile-unsigned.ipa .
          cd ..
          mv AcmeMobile-unsigned.ipa ../../AcmeMobile-unsigned.ipa

      - uses: actions/upload-artifact@v4
        with:
          name: AcmeMobile-unsigned
          path: apps/mobile/AcmeMobile-unsigned.ipa
