name: ios
on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        flavor: [dev, prod]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Enable corepack + install deps
        run: |
          corepack enable
          pnpm -v
          pnpm install

      # IMPORTANT: set live URL BEFORE sync so Info.plist gets it
      - name: Set live URL for dev
        if: matrix.flavor == 'dev'
        run: echo "CAPACITOR_LIVE_URL=${{ vars.DEV_SERVER_URL }}" >> $GITHUB_ENV

      # Ensure dist exists so `cap sync` won't fail
      # Option 1 (fast): placeholder index.html for dev
      - name: Create placeholder dist (dev)
        if: matrix.flavor == 'dev'
        run: |
          mkdir -p mobile/dist
          printf '<!doctype html><html><head><meta charset="utf-8"><title>dev</title></head><body>dev</body></html>' > mobile/dist/index.html

      # Option 2 (prod): real build + copy
      - name: Build web (prod)
        if: matrix.flavor == 'prod'
        working-directory: mobile
        run: |
          pnpm build
          npx cap copy ios

      - name: Add iOS platform
        working-directory: mobile
        run: npx cap add ios

      - name: Sync Capacitor (updates iOS project + copies web assets)
        working-directory: mobile
        run: npx cap sync ios

      - name: Allow HTTP for dev in Info.plist
        if: matrix.flavor == 'dev'
        working-directory: mobile
        run: |
          /usr/libexec/PlistBuddy -c "Add :NSAppTransportSecurity dict" ios/App/App/Info.plist || true
          /usr/libexec/PlistBuddy -c "Add :NSAppTransportSecurity:NSAllowsArbitraryLoads bool YES" ios/App/App/Info.plist || true

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods -N
          cd mobile/ios/App
          pod install

      - name: Xcode build (unsigned)
        run: |
          set -e
          cd mobile
          xcodebuild -workspace ios/App/App.xcworkspace
